[project]
name = "gridcoveringpuzzle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "highspy>=1.11.0",
    "ortools>=9.14.6206",
    "pyomo>=6.9.4",
]
